### ISSUE TITLE
Paginator doesn't work

### ISSUE THREAD

**Issue by kb1995** [ReeceM/prismic-sitemap#14]
**Describe the bug**

I just started working on an existing codebase which uses this package. There are more than a 100 articles, but only the first 100 articles are displayed in the sitemap (using the pageSize option of a 100).

I looked at the codebase and it looks like it's due to this conditional:

```
    if (total_pages > this.nextPage) {
      return this.paginate(type, page + 1)
    }
```

I don't think you set `nextPage` anywhere in the file, meaning that this condition will always be false. 

This is the conditional I've used in previous Prismic projects:

```
if (response.results_size + routes.length < response.total_results_size) {
```

I think this condition might work (but I haven't done any tests though):

```
    if (total_pages > next) {
      return this.paginate(type, page + 1)
    }
```

**Comment by ReeceM** [comment]
Hey @kb1995,

Thank you for picking this up 💯; it is very possible what you mentioned happened, I'll check the tests too in that case. 

I'll have a look at it this evening. 💯👍

**Comment by ReeceM** [comment]
Hey @kb1995, so the issue auto closed, but if you don't mind testing v0.4.1 when you can it would be cool.

If it doesn't please open the issue again 💯

**Comment by kb1995** [comment]
Hey @ReeceM, I just tested it and it works. Thanks for sorting out this issue so quickly!

**Comment by ReeceM** [comment]
Awesome, glad it is working 👏👏😁
