### ISSUE TITLE
Libraries that are listed as Dev Dependencies should be Dependencies

### ISSUE THREAD

**Issue by a-trost** [ReeceM/prismic-sitemap#3]
Right now in the `package.json` there are no dependencies, only devDependencies.

```
"dependencies": {},
  "devDependencies": {
    "cross-spawn": "^7.0.3",
    "jest": "^26.6.3",
    "next": "^10.0.7",
    "node-fetch": "^2.6.1",
    "prismic-javascript": "^3.0.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "sitemap": "^6.4.0"
  },
  ```
This causes them to not be installed in my project when I run `yarn add -D @reecem/prismic-sitemap`

`prismic-sitemap` has `prismic-javascript` listed as a dev dependency but uses it in `generator.js`, making the package required at runtime. 

I'm adding this to my next.js app, which uses `prismic-reactjs` instead of `prismic-javascript`, so that package isn't available. 
When I added `prismic-reactjs` to my project and tried to run again, I got the error:
```
Error: Cannot find module 'sitemap'
```

Luckily this is an easy fix and we just need to move the libraries that are required at runtime to the `dependencies` object.

**Comment by ReeceM** [comment]
Hey Alex, thank you for finding this.

I looked at where I installed the package to test, it was the project I extracted it from so I left parts of the dependencies 🤦‍♂️😅

It also appears that the error for `Error: Cannot find module 'sitemap'` is also because of the sitemap package being a `devDependency`. 

Thank you again for finding that. Will fix it soon \:)

**Comment by ReeceM** [comment]
I have fixed the issue of dependencies.

It will work in a fresh app next app. Just want to figure out what I broke in the tests, but did try the PR branch in an app :D

**Comment by ReeceM** [comment]
Hey @a-trost, just checking to see if this is working now for you?

I did get a fresh Next app to get setup with it and deployed. But want to make sure it is working for everyone else too.
